SELECT A.REST_ID, 
        B.REST_NAME, 
        B.FOOD_TYPE, 
        B.FAVORITES, 
        B.ADDRESS, 
        ROUND(AVG(A.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW A, REST_INFO B 
WHERE A.REST_ID = B.REST_ID
  AND B.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID, 
        B.REST_NAME, 
        B.FOOD_TYPE, 
        B.FAVORITES, 
        B.ADDRESS
ORDER BY SCORE DESC, B.FAVORITES DESC